name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run Pester tests
      run: |
        pwsh -Command "Install-Module Pester -Force -SkipPublisherCheck"
        pwsh -Command "Invoke-Pester -Path powershell_scripts/tests"

  sql_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SQL Server
      uses: lucas-vieira/setup-sql-server@v1
      with:
        sql-version: 2019
        sa-password: ${{ secrets.SA_PASSWORD }}

    - name: Run tSQLt tests
      run: |
        sqlcmd -S localhost -U sa -P ${{ secrets.SA_PASSWORD }} -i tests/Test_usp_GenerateClientOrderSummary.sql
